{
    "name": "SBM Sales Order",
    "version": "1.0",
    "depends": ["base","account","sale","sbm_inherit"],
    "author": "Suprabakti Mandiri",
    "category": "SBM Sales Order",
    "description": """Modul ini digunakan untuk Menggolah Create PB dari Sales Order""",
    "init_xml": [],
    'update_xml': ["saleorder_view.xml","setting.xml"],
    'demo_xml': [],
    'installable': True,
    'active': False,
    'certificate': '',
    # 'js':['static/src/js/product.js'],
}