{
    "name": "SBM Master Product",
    "version": "1.0",
    "depends": ["product","stock","sbm_inherit"],
    "author": "Suprabakti Mandiri",
    "category": "SBM Master Product",
    "description": """Modul ini digunakan untuk Menggolah Master Product""",
    "init_xml": [],
    'update_xml': ["product_view.xml"],
    'demo_xml': [],
    'installable': True,
    'active': False,
    'certificate': '',
    'js':['static/src/js/product.js'],
}