{
    "name": "SBM WORK ORDER",
    "version": "1.0",
    "depends": ["base","mrp","sale","product","stock","sbm_order_preparation","sbm_delivery_note","new_sbm_sale_order"],
    "author": "PT.SUPRABAKTI MANDIRI",
    "category": "WORK ORDER",
    "description": """Modul ini digunakan untuk Menggolah SPK PT.Suprabakti Mandiri""",
    "init_xml": [],
    'update_xml': ["work_order_view.xml","adhoc_order_request_view.xml","setting.xml"],
    'demo_xml': [],
    'installable': True,
    'active': False,
    'certificate': '',
    'js':['static/src/js/work_order.js'],
}