{
	"name": "Purchase Order Import",
	"version": "1.0",
	"depends": [
				"base",
				"purchase",
				"hr",
				"product",
				"sbm_purchase",
				"sbm_discount",
				"sbm_purchaseorder",
				"sbm_inherit",
				"ad_purchase_import",
				],
	"author": "Suprabakti Mandiri",
	"category": "Purchase Suprabakti",
	"description": """Modul ini digunakan untuk Menggolah Data Purchase Order Import""",
	"init_xml": [],
	'update_xml': ["purchase_import.xml"],
	'demo_xml': [],
	'installable': True,
	'active': False,
	'certificate': '',
}