{
    "name": "Order Packaging",
    "version": "1.0",
    "depends": ["base","sale","stock"],
    "author": "ADSOFT",
    "category": "Sale Order",
    "description": """ Provide Print Button in Various Format """,
    "init_xml": [],
    'update_xml': ["preparation_view.xml"],
    'demo_xml': [],
    'installable': True,
    'active': False,
    'certificate': '',
    'js':['static/src/js/order_preparation.js'],
}
